management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

server:
  port: 8089

spring:
  data:
    mongodb:
      mapping:
      uri: mongodb+srv://ebarrientos:rlD4McyEGxim5Ev2@clusterise.59mtk0v.mongodb.net/test?retryWrites=true&w=majority&appName=ClusterISE
  application:
    name: appmongo

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

token:
  signin:
    key: 2ae3caf0db25c9e19adf43b7e206a54223986cc477a2f4de3c5a8d2377f66efd
